use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Parser, Debug)]
#[command(
    name = "xtask",
    about = "CAFramework internal developer and scaffolding tool"
)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Codegen frontend and Rust files from app.toml
    Codegen {
        #[arg(short, long, default_value = "app.toml")]
        config: PathBuf,
    },
    /// Scaffold a new app from CAFramework base template
    NewApp {
        #[arg(short, long, default_value = "app.toml")]
        config: PathBuf,
        #[arg(short, long)]
        out: PathBuf,
        #[arg(long)]
        with_sample: bool,
        #[arg(long)]
        dry_run: bool,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppConfig {
    pub app: AppMeta,
    pub window: WindowConfig,
    pub security: SecurityConfig,
    pub modules: ModulesConfig,
    pub roles: RolesConfig,
    pub menus: Vec<MenuItem>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppMeta {
    pub name: String,
    pub slug: String,
    pub bundle_id: String,
    pub version: String,
    pub accent_color: String,
    pub error_prefix: String,
    pub description: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WindowConfig {
    pub title: String,
    pub width: u32,
    pub height: u32,
    pub min_width: u32,
    pub min_height: u32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SecurityConfig {
    pub master_password_required: bool,
    pub profile_pin_enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModulesConfig {
    pub sample_slice_enabled: bool,
    pub ai_assistant_enabled: bool,
    pub pro_licensing_enabled: bool,
    pub updater_enabled: bool,
    pub crash_reporting_enabled: bool,
    pub backup_restore_enabled: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RolesConfig {
    pub default_role: String,
    pub allowed_roles: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MenuItem {
    pub key: String,
    pub label: String,
    pub href: String,
    pub icon: String,
    pub description: String,
}

fn load_config(path: &Path) -> Result<AppConfig, Box<dyn std::error::Error>> {
    let content = fs::read_to_string(path)?;
    let cfg: AppConfig = toml::from_str(&content)?;
    if cfg.menus.is_empty() {
        return Err("app.toml must contain at least one menu entry".into());
    }
    Ok(cfg)
}

fn run_codegen(config_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let cfg = load_config(config_path)?;
    let root = config_path.parent().unwrap_or_else(|| Path::new("."));

    // 1. Generate frontend/src/lib/generated/app.ts
    let gen_dir = root.join("frontend/src/lib/generated");
    fs::create_dir_all(&gen_dir)?;

    let app_ts_content = format!(
        r#"// THIS FILE IS AUTOMATICALLY GENERATED BY `cargo xtask codegen`. DO NOT EDIT MANUALLY.

export const APP_CONFIG = {{
  name: {:?},
  slug: {:?},
  bundleId: {:?},
  version: {:?},
  accentColor: {:?},
  errorPrefix: {:?},
  description: {:?},
  window: {{
    title: {:?},
    width: {},
    height: {},
    minWidth: {},
    minHeight: {}
  }},
  security: {{
    masterPasswordRequired: {},
    profilePinEnabled: {}
  }},
  modules: {{
    sampleSliceEnabled: {},
    aiAssistantEnabled: {},
    proLicensingEnabled: {},
    updaterEnabled: {},
    crashReportingEnabled: {},
    backupRestoreEnabled: {}
  }},
  roles: {{
    defaultRole: {:?},
    allowedRoles: {:?}
  }}
}} as const;
"#,
        cfg.app.name,
        cfg.app.slug,
        cfg.app.bundle_id,
        cfg.app.version,
        cfg.app.accent_color,
        cfg.app.error_prefix,
        cfg.app.description,
        cfg.window.title,
        cfg.window.width,
        cfg.window.height,
        cfg.window.min_width,
        cfg.window.min_height,
        cfg.security.master_password_required,
        cfg.security.profile_pin_enabled,
        cfg.modules.sample_slice_enabled,
        cfg.modules.ai_assistant_enabled,
        cfg.modules.pro_licensing_enabled,
        cfg.modules.updater_enabled,
        cfg.modules.crash_reporting_enabled,
        cfg.modules.backup_restore_enabled,
        cfg.roles.default_role,
        cfg.roles.allowed_roles,
    );
    fs::write(gen_dir.join("app.ts"), app_ts_content)?;

    // 2. Generate frontend/src/lib/generated/navItems.generated.ts
    let mut nav_items_ts = String::from(
        r#"// THIS FILE IS AUTOMATICALLY GENERATED BY `cargo xtask codegen`. DO NOT EDIT MANUALLY.

export interface GeneratedNavItem {
  key: string;
  label: string;
  href: string;
  icon: string;
  description: string;
  path: string;
}

export const GENERATED_NAV_ITEMS: GeneratedNavItem[] = [
"#,
    );

    for m in &cfg.menus {
        let path_svg = match m.icon.as_str() {
            "notes" => {
                "M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-5 14H7v-2h7v2zm3-4H7v-2h10v2zm0-4H7V7h10v2z"
            }
            "cash" | "wallet" => {
                "M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z"
            }
            _ => "M4 6h16M4 12h16M4 18h16",
        };
        nav_items_ts.push_str(&format!(
            "  {{\n    key: {:?},\n    label: {:?},\n    href: {:?},\n    icon: {:?},\n    description: {:?},\n    path: {:?}\n  }},\n",
            m.key, m.label, m.href, m.icon, m.description, path_svg
        ));
    }
    nav_items_ts.push_str("];\n");
    fs::write(gen_dir.join("navItems.generated.ts"), nav_items_ts)?;

    println!("Codegen completed successfully for {}", cfg.app.name);
    Ok(())
}

fn run_new_app(
    config_path: &Path,
    out_dir: &Path,
    _with_sample: bool,
    dry_run: bool,
) -> Result<(), Box<dyn std::error::Error>> {
    let cfg = load_config(config_path)?;
    println!(
        "Scaffolding new app '{}' ({}) into {:?}",
        cfg.app.name, cfg.app.slug, out_dir
    );

    if out_dir.exists() && out_dir.read_dir()?.next().is_some() {
        return Err(format!("Target directory {:?} is not empty!", out_dir).into());
    }

    if dry_run {
        println!("Dry run mode enabled. No files written.");
        return Ok(());
    }

    // Recursively copy base repo, excluding git and build targets
    let template_root = config_path.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(out_dir)?;

    for entry in walkdir::WalkDir::new(template_root) {
        let entry = entry?;
        let path = entry.path();
        let rel_path = path.strip_prefix(template_root)?;

        let rel_str = rel_path.to_string_lossy();
        if rel_str.starts_with(".git")
            || rel_str.starts_with("target")
            || rel_str.starts_with("frontend/node_modules")
            || rel_str.starts_with("frontend/.svelte-kit")
            || rel_str.starts_with("frontend/build")
            || rel_str.contains("evidence")
        {
            continue;
        }

        let dest = out_dir.join(rel_path);
        if path.is_dir() {
            fs::create_dir_all(&dest)?;
        } else if path.is_file() {
            let file_name = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
            if file_name.ends_with(".rs")
                || file_name.ends_with(".toml")
                || file_name.ends_with(".json")
                || file_name.ends_with(".svelte")
                || file_name.ends_with(".ts")
                || file_name.ends_with(".md")
            {
                let content = fs::read_to_string(path)?;
                let replaced = content
                    .replace("CAFramework", &cfg.app.name)
                    .replace("caframework", &cfg.app.slug)
                    .replace("com.fathforce.caframework", &cfg.app.bundle_id)
                    .replace("CAF", &cfg.app.error_prefix);
                fs::write(&dest, replaced)?;
            } else {
                fs::copy(path, &dest)?;
            }
        }
    }

    // Write app.toml to target
    fs::copy(config_path, out_dir.join("app.toml"))?;

    // Run codegen in target
    run_codegen(&out_dir.join("app.toml"))?;

    println!("Successfully scaffolded {} at {:?}", cfg.app.name, out_dir);
    Ok(())
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let cli = Cli::parse();
    match cli.command {
        Commands::Codegen { config } => run_codegen(&config),
        Commands::NewApp {
            config,
            out,
            with_sample,
            dry_run,
        } => run_new_app(&config, &out, with_sample, dry_run),
    }
}
